In [3]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [14]:
import pandas as pd
from src.preprocessing import clean_text
from src.model import train_model
from sklearn.model_selection import train_test_split

Reading the data

In [6]:
df = pd.read_csv("../data/raw/articles.csv")
df.head()

,title,text,date,category,subcategory,link
0,"Lula diz que está 'lascado', mas que ainda tem...",Com a possibilidade de uma condenação impedir ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
1,"'Decidi ser escrava das mulheres que sofrem', ...","Para Oumou Sangaré, cantora e ativista malines...",2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
2,Três reportagens da Folha ganham Prêmio Petrob...,Três reportagens da Folha foram vencedoras do ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
3,Filme 'Star Wars: Os Últimos Jedi' ganha trail...,A Disney divulgou na noite desta segunda-feira...,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
4,CBSS inicia acordos com fintechs e quer 30% do...,"O CBSS, banco da holding Elopar dos sócios Bra...",2017-09-10,mercado,NaN,http://www1.folha.uol.com.br/mercado/2017/10/1...

Preprocessing

In [8]:
df = df.dropna(subset=["text"])
df["text"] = df["text"].apply(clean_text)

In [10]:
df.head()

,title,text,date,category,subcategory,link
0,"Lula diz que está 'lascado', mas que ainda tem...",com a possibilidade de uma condenação impedir ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
1,"'Decidi ser escrava das mulheres que sofrem', ...",para oumou sangaré cantora e ativista malinesa...,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
2,Três reportagens da Folha ganham Prêmio Petrob...,três reportagens da folha foram vencedoras do ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
3,Filme 'Star Wars: Os Últimos Jedi' ganha trail...,a disney divulgou na noite desta segunda feira...,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
4,CBSS inicia acordos com fintechs e quer 30% do...,o cbss banco da holding elopar dos sócios brad...,2017-09-10,mercado,NaN,http://www1.folha.uol.com.br/mercado/2017/10/1...

Training the Model

In [12]:
X = df["text"]
y = df["category"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    
)

In [19]:
import sys
sys.path.append("../src")

from model import train_model

In [20]:
model, vectorizer = train_model(X_train, y_train)

c:\Users\matth\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
from sklearn.metrics import classification_report

X_test_vec = vectorizer.transform(X_test)
y_pred = model.predict(X_test_vec)

print(classification_report(y_test, y_pred))

c:\Users\matth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\matth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                              precision    recall  f1-score   support

                    ambiente       0.52      0.26      0.35       102
                      asmais       0.00      0.00      0.00       111
              banco-de-dados       0.00      0.00      0.00        13
                         bbc       0.78      0.14      0.24       223
               cenarios-2017       0.00      0.00      0.00         8
                     ciencia       0.62      0.59      0.61       276
                     colunas       0.77      0.81      0.79      4328
                      comida       0.62      0.41      0.49       155
                   cotidiano       0.82      0.91      0.86      3378
                          dw       0.00      0.00      0.00        12
                    educacao       0.79      0.77      0.78       433
          empreendedorsocial       0.87      0.65      0.74       158
            equilibrioesaude       0.64      0.55      0.59       280
                    especial       0.00      0.00      0.00        12
                     esporte       0.95      0.96      0.96      3945
                    euronews       0.00      0.00      0.00         2
                    folhinha       0.83      0.47      0.60       187
guia-de-livros-discos-filmes       0.00      0.00      0.00        28
guia-de-livros-filmes-discos       0.00      0.00      0.00         7
                   ilustrada       0.79      0.91      0.84      3083
                ilustrissima       0.71      0.20      0.31       299
                infograficos       0.00      0.00      0.00         7
                     mercado       0.83      0.87      0.85      4186
                      mulher       0.00      0.00      0.00         4
                  multimidia       0.00      0.00      0.00         5
                       mundo       0.86      0.93      0.89      3412
       o-melhor-de-sao-paulo       0.00      0.00      0.00        34
                     opiniao       0.97      0.84      0.90       877
              paineldoleitor       0.99      0.95      0.97       800
                       poder       0.87      0.91      0.89      4374
                         rfi       0.00      0.00      0.00         8
                    saopaulo       0.82      0.72      0.77       816
             seminariosfolha       0.72      0.17      0.27        78
                    serafina       0.00      0.00      0.00        73
                   sobretudo       0.87      0.57      0.69       207
                         tec       0.73      0.61      0.67       453
                   topofmind       1.00      0.06      0.11        17
                 treinamento       0.00      0.00      0.00         3
    treinamentocienciaesaude       0.00      0.00      0.00         4
                     turismo       0.77      0.66      0.71       370
                          tv       0.85      0.48      0.62       464
                        vice       0.00      0.00      0.00        26

                    accuracy                           0.84     33258
                   macro avg       0.48      0.37      0.39     33258
                weighted avg       0.83      0.84      0.83     33258

c:\Users\matth\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Saving the model

In [29]:
import os

os.makedirs("../models", exist_ok=True)

In [30]:
import joblib

joblib.dump((model, vectorizer), "../models/model.pkl")

['../models/model.pkl']